name: Deploy Next.js App to Digital Ocean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: roottask.com
          username: root
          password: sN91#r5wNIqz
          source: ".next/,public/,package.json,package-lock.json,next.config.js,ecosystem.config.js"
          target: "/var/www/html/"
          strip_components: 0

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: roottask.com
          username: root
          password: sN91#r5wNIqz
          script: |
            cd /var/www/html
            # Load nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # Remove old .next directory if it exists
            rm -rf .next
            # Install production dependencies
            npm install --production
            # Ensure proper permissions
            chown -R root:root /var/www/html
            chmod -R 755 /var/www/html
            # Create logs directory
            mkdir -p logs
            # Restart the application using PM2
            pm2 delete card-tree || true
            pm2 start ecosystem.config.js
            pm2 save
