name: Deploy Next.js App to Digital Ocean Droplet
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Increase Node.js memory limit for build
          export NODE_OPTIONS="--max-old-space-size=4096"
          # Build with production optimization
          npm run build -- --no-lint

      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: roottask.com
          username: root
          password: sN91#r5wNIqz
          source: ".next/,public/,package.json,package-lock.json,next.config.js,ecosystem.config.js"
          target: "/var/www/html/"
          strip_components: 0

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: roottask.com
          username: root
          password: sN91#r5wNIqz
          script: |
            cd /var/www/html

            # Load nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Set memory limit for Node.js
            export NODE_OPTIONS="--max-old-space-size=512"

            # Install only production dependencies
            npm ci --production

            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Create logs directory
            mkdir -p logs

            # Stop and delete existing process
            pm2 delete card-tree || true

            # Start the application with memory limit
            pm2 start ecosystem.config.js

            # Save PM2 configuration
            pm2 save
